version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    volumes:
      - "./:/var/www/html"
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PMA_USER: root
      PMA_PASSWORD: wordpress

  searchreplacedb:
    image: proq/search-replace-db
    links:
      - db
    ports:
      - "8081:80"
    depends_on:
      - db
      - wordpress
    volumes:
      - ./:/var/www/wp_html
